name: jetbot-command-centre-dev

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        BUILDPLATFORM: ${BUILDPLATFORM:-linux/arm64}
    image: jetbot-command-centre:dev
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - /dev:/dev
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - COOKIE_SECRET=${COOKIE_SECRET:-dev_secret_key}
      - DEBUG=1
      - WATCHFILES=1
    ports:
      - "8888:8888"
      - "5678:5678"  # For Python debugger
    privileged: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]