name: jetbot-command-centre

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDPLATFORM: ${BUILDPLATFORM:-linux/arm64}
      labels:
        org.opencontainers.image.source: https://github.com/Shival-Gupta/jetbot-command-centre
    image: ${DOCKER_REGISTRY:-ghcr.io}/shival-gupta/jetbot-command-centre:${TAG:-latest}
    platform: ${PLATFORM:-linux/arm64}
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    volumes:
      - /dev:/dev
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - COOKIE_SECRET=${COOKIE_SECRET:-change_this_to_a_random_secret}
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
