version: '3.8'

services:
  jetbot-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/shival-gupta/jetbot-command-centre:arm64
    restart: always
    network_mode: "host"
    privileged: true
    volumes:
      - /dev:/dev
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - COOKIE_SECRET=${COOKIE_SECRET:-change_this_to_a_random_secret}
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]